export type Channel='map'|'left'|'right'|'etco2'|'spo2'|'hr';
export type Side='left'|'right';
export interface Config {map_quality_enabled:boolean;map_review_low:number;map_review_high:number;map_error_codes:number[];block_seconds:number;window_seconds:number;step_seconds:number;min_block_coverage:number;sensitivity:boolean;min_pair_ratio:number;start:number;end:number|null;sides:Side[];map_bin_width:number;reference:number|null;use_annotations:boolean;ceiling_hint:boolean;ceiling_value:number;exclude_suspect:boolean;jump_map:number;jump_rso2:number;numerical_sd_tolerance:number;low_sd_map:number;low_sd_rso2:number;}
export const defaults:Config={map_quality_enabled:true,map_review_low:20,map_review_high:200,map_error_codes:[],block_seconds:10,window_seconds:300,step_seconds:10,min_block_coverage:.8,sensitivity:false,min_pair_ratio:.8,start:0,end:null,sides:['left','right'],map_bin_width:5,reference:null,use_annotations:true,ceiling_hint:true,ceiling_value:95,exclude_suspect:false,jump_map:30,jump_rso2:15,numerical_sd_tolerance:1e-10,low_sd_map:1,low_sd_rso2:.5};
export interface Summary {selected_seconds:number;raw_overlap_seconds:number;quality_seconds:number;computable_seconds:number;no_result_seconds:number;valid_outputs:number;null_reasons:Record<string,number>;above_reference_fraction:number|null;}
export interface Case {caseid:number;age:number|null;opname:string|null;opstart:number|null;opend:number|null;anestart:number|null;aneend:number|null;caseend:number;tracks:Record<string,{tname:string;tid:string;unit:string;nominal_interval:number}>;cached:boolean;quality:{accepted:boolean;summary:Record<Side,Summary>}|null;population:string;}
export interface BlockValue {mean:number|null;coverage:number;count:number;valid:boolean;flags:string[];span_seconds:number;max_uncovered_seconds:number;}
export interface Block {start:number;end:number;map:BlockValue;left:BlockValue;right:BlockValue;}
export interface Window {window_id:string;start:number;end:number;side:Side;cox:number|null;valid_pairs:number;expected_pairs:number;required_pairs:number;sd_map:number|null;sd_rso2:number|null;mean_map:number|null;mean_rso2:number|null;reasons:string[];hints:string[];}
export interface Pair {start:number;end:number;map:number|null;rso2:number|null;valid:boolean;flags:string[];map_coverage:number;rso2_coverage:number;}
export interface Explanation extends Window {pairs:Pair[];interpretation:string;config_hash:string;}
export interface Run {map_quality?:{version:number;rows:number;invalid_points:number;review_points:number;sha256:string};run_id:string;config_hash:string;input_hash:string;mode:'real'|'synthetic';config:Config;range:{start:number;end:number};blocks:Block[];windows:Window[];summary:Record<Side,Summary>;manifest:{case:Case;generator?:Record<string,unknown>;tracks:Record<string,Record<string,unknown>>};map_bins:{side:Side;map_low:number;map_high:number;mean_cox:number;median_cox:number;support_seconds:number;outputs:number;low_coverage:boolean}[];annotations:Annotation[];}
export interface Annotation {id?:string;channel:Channel|'all';start:number;end:number;reason:string;operator?:string;created_at?:string;}
export type Signals=Partial<Record<Channel,{time:number;value:number|null;valid:boolean;flags:string;MAP_raw?:number|null;MAP_clean?:number|null;quality_flag?:string}[]>>;
export const names:Record<Channel,string>={map:'有创 MAP',left:'左侧 rSO₂',right:'右侧 rSO₂',etco2:'EtCO₂',spo2:'SpO₂',hr:'心率'};
export const colors:Record<Channel,string>={map:'#4265a2',left:'#158589',right:'#ab7947',etco2:'#8267a3',spo2:'#6f8b50',hr:'#8f6475'};
export const reasonNames:Record<string,string>={range_ok:'通过数值范围检查',legacy_available:'历史规则可用',source_invalid:'来源无效标志',device_error_code:'已配置设备错误码',map_negative:'MAP负值无效',map_zero_review:'MAP零值需复核',map_low_review:'MAP极端低值需复核',map_high_review:'MAP极端高值需复核',warmup:'预热不足',insufficient_pairs:'合格配对不足',zero_variance:'零方差：相关未定义',low_variation:'低变异，谨慎解释',window_has_gaps:'窗口含缺口',coverage_insufficient:'覆盖不足',range_boundary:'范围边界不完整',no_observations:'没有观测',long_gap:'长缺口',nonfinite:'非有限值',timestamp_conflict:'重复时间戳冲突',manual_exclusion:'人工排除',jump_suspect:'可疑跳变',ceiling_candidate:'候选上限',flat_suspect:'块内平坦',extreme_suspect:'极端值提示'};
export const fmt=(n:number|null|undefined,d=3)=>n==null?'—':n.toFixed(d);
export const minutes=(n:number)=>`${(n/60).toFixed(1)} 分钟`;

export interface RawChannelSummary {observations:number;finite_observations:number;nonfinite_observations:number;nonfinite_fraction:number|null;minimum:number|null;maximum:number|null;mean:number|null;sample_sd:number|null;}
export type RawSummary=Record<'map'|'left'|'right',RawChannelSummary>;
