import {test,expect} from '@playwright/test';

test('COx 连续滚轮缩放与平移绘制',async({page})=>{
 await page.setViewportSize({width:1440,height:1800});
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await page.getByRole('button',{name:'合成信号实验室'}).click();
 const response=page.waitForResponse(r=>/\/api\/analyses\/[a-f0-9]{64}$/.test(r.url())&&r.ok());
 await page.getByRole('button',{name:'运行实验',exact:true}).click();
 const run=await(await response).json();
 await page.getByRole('button',{name:/05 看整段 COx/}).click();
 await page.getByLabel('横轴时间显示').selectOption('elapsed');
 const chart=page.getByRole('img',{name:'左右 COx 与无结果点，可点击每一个输出查看窗口',exact:true});
 await expect(chart).toBeVisible();await expect(page.locator('.busy')).toHaveCount(0);
 await expect(chart.locator('svg')).toHaveCount(1);await expect(chart.locator('canvas')).toHaveCount(0);
 const paths=()=>chart.locator('svg path').evaluateAll(elements=>[['#158589','rgb(23,146,150)'],['#ab7947','rgb(188,133,78)']].map(colors=>elements.filter(e=>colors.includes(e.getAttribute('stroke')??'')&&e.getAttribute('fill')==='none'&&(e.getAttribute('d')?.length??0)>100).map(e=>e.getAttribute('d'))));
 const initial=await paths();expect(initial.map(p=>p.length)).toEqual([1,1]);
 const range=chart.locator('..').locator('.chart-visible-range'),before=await range.innerText();
 await chart.scrollIntoViewIfNeeded();await page.mouse.move(0,0);
 await chart.screenshot({path:'../artifacts/19-cox-svg-before.png'});
 const box=(await chart.boundingBox())!;
 const highlight=page.getByTestId('raw-window-highlight'),rawRange=page.locator('.signal-card .chart-visible-range');
 const panel=page.getByTestId('raw-data-panel'),windowRows=panel.locator('tr.raw-row-window');
 await expect(panel.locator('.raw-time-button').first()).toBeAttached();
 const pinned=await highlight.innerText(),rawBefore=await rawRange.innerText();
 let windowRequests=0,signalRequests=0;page.on('request',r=>{if(r.url().includes('/windows/'))windowRequests++;if(r.url().includes('/signals'))signalRequests++;});
 const point=run.windows.find((w:any)=>w.side==='left'&&w.end>=900&&w.cox!==null);
 await page.mouse.move(box.x+58+(point.end/1800)*(box.width-86),box.y+34+(1-point.cox)/2.15*(265-82));
 await expect(highlight).toHaveAttribute('data-start',String(point.start));
 await expect(highlight).toHaveAttribute('data-end',String(point.end));
 await expect(highlight).toContainText('00:10:00–00:15:00');
 await expect(rawRange).toHaveText(rawBefore);await expect(range).toHaveText(before);
 await expect(windowRows.first().locator('button')).toHaveAttribute('title','原始时间：600 秒');
 const times=await windowRows.locator('button').evaluateAll(buttons=>buttons.map(b=>Number(b.getAttribute('title')!.match(/原始时间：(.*) 秒/)![1])));
 expect(times.length).toBeGreaterThan(1);expect(times.every(t=>t>=point.start&&t<point.end)).toBeTruthy();
 const firstRow=(await windowRows.first().boundingBox())!,scroll=(await panel.locator('.raw-table-scroll').boundingBox())!;
 expect(firstRow.y).toBeGreaterThan(scroll.y+20);expect(firstRow.y+firstRow.height).toBeLessThanOrEqual(scroll.y+scroll.height);
 await page.locator('.signal-card').screenshot({path:'../artifacts/22-cox-hover-table.png'});
 await page.mouse.move(0,0);await expect(highlight).toHaveText(pinned);
 await expect(windowRows).toHaveCount(0);
 // Null outputs still represent actual windows and preview them without fetching details.
 const missing=run.windows.find((w:any)=>w.side==='left'&&w.cox===null);
 await page.mouse.move(box.x+58+(missing.end/1800)*(box.width-86),box.y+34+2.1/2.15*(265-82));
 await expect(highlight).toHaveAttribute('data-start',String(missing.start));
 await expect(highlight).toHaveAttribute('data-end',String(missing.end));
 await expect(highlight).toContainText('无结果');
 await expect(windowRows.first().locator('button')).toHaveAttribute('title','原始时间：0 秒');
 const endRows=panel.locator('tbody tr').filter({has:page.locator(`button[title="原始时间：${missing.end} 秒"]`)});
 expect(await endRows.count()).toBeGreaterThan(0);
 for(const row of await endRows.all())await expect(row).not.toHaveClass(/raw-row-window/);
 await page.mouse.move(0,0);await expect(highlight).toHaveText(pinned);
 await expect(windowRows).toHaveCount(0);expect(windowRequests).toBe(0);expect(signalRequests).toBe(0);
 await page.mouse.move(box.x+58+(point.end/1800)*(box.width-86),box.y+34+(1-point.cox)/2.15*(265-82));
 for(let i=0;i<12;i++){await page.mouse.wheel(0,-20);await page.waitForTimeout(35);}
 await page.waitForTimeout(300);
 await expect(range).not.toHaveText(before);
 const zoomed=await paths();
 expect(zoomed.map(p=>p.length)).toEqual([1,1]);expect(zoomed).not.toEqual(initial);
 await chart.screenshot({path:'../artifacts/19-cox-svg-zoom-hover.png'});
 const beforePan=await range.innerText();
 await page.mouse.move(box.x+box.width*.5,box.y+110);await page.mouse.down();
 await page.mouse.move(box.x+box.width*.6,box.y+110,{steps:12});await page.mouse.up();
 await expect(range).not.toHaveText(beforePan);
 expect((await paths()).map(p=>p.length)).toEqual([1,1]);
 await page.mouse.move(0,0);await page.waitForTimeout(300);
 await chart.screenshot({path:'../artifacts/19-cox-svg-pan.png'});
 await expect(highlight).toHaveText(pinned);
 expect(errors).toEqual([]);
});

test('A/B 悬停使用各自保存的窗口长度',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'合成信号实验室'}).click();
 const response=()=>page.waitForResponse(r=>/\/api\/analyses\/[a-f0-9]{64}$/.test(r.url())&&r.ok());
 const aResponse=response();await page.getByRole('button',{name:'运行实验',exact:true}).click();
 const a=await(await aResponse).json();await expect(page.locator('.busy')).toHaveCount(0);
 await page.getByRole('button',{name:/06 做参数对比/}).click();
 await page.getByRole('button',{name:'将当前运行固定为 A'}).click();
 await page.getByLabel('窗口秒数').selectOption('600');
 const bResponse=response();await page.getByRole('button',{name:'计算运行 B',exact:true}).click();
 const b=await(await bResponse).json();await expect(page.locator('.busy')).toHaveCount(0);
 const chart=page.getByRole('img',{name:'左右 COx 与无结果点，可点击每一个输出查看窗口',exact:true});
 const highlight=page.getByTestId('raw-window-highlight');
 await page.getByLabel('原始表通道').selectOption('left');
 await chart.scrollIntoViewIfNeeded();
 await chart.locator('svg').getByText('左侧 COx',{exact:true}).click();await chart.locator('svg').getByText('右侧 COx',{exact:true}).click();
 const hover=async(run:any)=>{const w=run.windows.find((w:any)=>w.side==='left'&&w.end===900);expect(w.cox).not.toBeNull();const box=(await chart.boundingBox())!;await page.mouse.move(box.x+58+.5*(box.width-86),box.y+34+(1-w.cox)/2.15*(265-82));await expect(highlight).toHaveAttribute('data-start',String(w.start));await expect(highlight).toHaveAttribute('data-end','900');};
 await hover(a);await expect(highlight).toContainText('运行 A');await expect(highlight).toHaveAttribute('data-start','600');
 await expect(page.getByLabel('原始表通道')).toHaveValue('left');
 await expect(page.locator('tr.raw-row-window').first().locator('button')).toHaveAttribute('title','原始时间：600 秒');
 await chart.locator('svg').getByText('运行 A · 左',{exact:true}).click();await chart.locator('svg').getByText('左侧 COx',{exact:true}).click();
 await hover(b);await expect(highlight).toContainText('左侧 COx');await expect(highlight).toHaveAttribute('data-start','300');
 await expect(page.locator('tr.raw-row-window').first().locator('button')).toHaveAttribute('title','原始时间：300 秒');
 await page.getByRole('button',{name:/03 做时间平均/}).click();await expect(highlight).not.toContainText('悬停窗口');
});
