import {test,expect} from '@playwright/test';

test('MAP学习规则、清洗表和可追溯导出',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.getByRole('button',{name:'合成信号实验室'}).click();
 const firstResponse=page.waitForResponse(r=>/\/api\/analyses\/[a-f0-9]{64}$/.test(r.url())&&r.ok());
 await page.getByRole('button',{name:'运行实验',exact:true}).click();
 const first=await(await firstResponse).json();await expect(page.locator('.busy')).toHaveCount(0);
 const raw=await(await page.request.get(`/api/analyses/${first.run_id}/signals?full=true`)).json();
 const code=raw.signals.map[0].value;
 await page.getByRole('button',{name:/02 检查质量/}).click();
 const panel=page.getByTestId('map-quality-learning');
 await expect(panel.getByLabel('MAP低值复核界限')).toBeHidden();
 await panel.getByRole('button',{name:'展开 MAP 质控学习'}).click();
 await expect(panel.getByLabel('MAP低值复核界限')).toHaveValue('20');
 await expect(panel.getByLabel('MAP高值复核界限')).toHaveValue('200');
 await panel.getByLabel('MAP低值复核界限').fill('250');
 await expect(panel.getByRole('alert')).toContainText('下限 < 上限');
 await expect(panel.getByRole('button',{name:'应用 MAP 质控并重算'})).toBeDisabled();
 await panel.getByLabel('MAP低值复核界限').fill('20');
 await panel.getByLabel('MAP高值复核界限').fill('60');
 await panel.getByRole('button',{name:'收起 MAP 质控学习'}).click();
 await expect(panel.getByLabel('MAP高值复核界限')).toBeHidden();
 await expect(panel).toContainText('有待重算修改');
 await panel.getByRole('button',{name:'展开 MAP 质控学习'}).click();
 await expect(panel.getByLabel('MAP高值复核界限')).toHaveValue('60');
 await panel.locator('summary').click();
 await panel.getByLabel('MAP设备错误码').fill(String(code));
 await panel.getByRole('button',{name:'添加错误码',exact:true}).click();
 await expect(panel).toContainText('上述参数尚未应用');
 const secondResponse=page.waitForResponse(r=>/\/api\/analyses\/[a-f0-9]{64}$/.test(r.url())&&r.ok());
 await panel.getByRole('button',{name:'应用 MAP 质控并重算'}).click();
 const second=await(await secondResponse).json();await expect(page.locator('.busy')).toHaveCount(0);
 expect(second.run_id).not.toBe(first.run_id);expect(second.config.map_error_codes).toEqual([code]);
 expect(second.map_quality.invalid_points).toBeGreaterThan(0);expect(second.map_quality.review_points).toBeGreaterThan(0);
 const cleaned=await(await page.request.get(`/api/analyses/${second.run_id}/signals?full=true`)).json();
 expect(cleaned.signals.map[0].MAP_raw).toBe(code);expect(cleaned.signals.map[0].MAP_clean).toBeNull();
 for(const p of cleaned.signals.map.filter((p:any)=>p.valid))expect(p.MAP_clean).toBe(p.MAP_raw);
 await page.getByLabel('原始表通道').selectOption('map');
 const table=page.getByTestId('raw-data-panel');
 await expect(table.getByRole('columnheader',{name:'MAP_clean',exact:true})).toBeVisible();
 await expect(table.locator('tbody tr').first().locator('td').nth(3)).toHaveText('NaN');
 await table.screenshot({path:'../artifacts/25-map-clean-table.png'});
 const csv=await page.request.get(`/api/analyses/${second.run_id}/map-quality`);
 expect(csv.ok()).toBeTruthy();expect(await csv.text()).toContain('time,MAP_raw,MAP_clean,quality_flag,valid');
 const download=page.waitForEvent('download');await panel.getByRole('link',{name:/下载 MAP 原始值/}).click();
 expect((await download).suggestedFilename()).toMatch(/^map-quality-.*\.csv$/);
 await panel.locator('summary').click();await panel.screenshot({path:'../artifacts/26-map-quality-learning.png'});
 expect(errors).toEqual([]);
});
