import {test,expect} from '@playwright/test';

test('完整原始点、显示缓存与刷新恢复本地运行',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const signalRequests:string[]=[];page.on('request',r=>{if(/\/api\/analyses\/[a-f0-9]{64}\/signals/.test(r.url()))signalRequests.push(r.url());});
 await page.goto('/');await page.getByRole('button',{name:'选择病例',exact:true}).click();
 await page.getByRole('button',{name:'选择病例 251',exact:true}).click();
 const fullResponse=page.waitForResponse(r=>r.url().endsWith('/signals?full=true')&&r.ok());
 await page.getByRole('button',{name:'分析本地数据',exact:true}).click();
 await expect(page.locator('.busy')).toHaveCount(0,{timeout:60000});
 await expect(page.getByRole('button',{name:'查看完整原始点',exact:true})).toBeEnabled();
 await page.locator('.sampling-info summary').click();
 await expect(page.locator('.sampling-info')).toContainText('4.91 s');
 await expect(page.locator('.sampling-info')).toContainText('0.50 Hz');
 const full=await(await fullResponse).json();
 await expect(page.getByTestId('raw-data-panel').getByRole('button',{name:'原始表下一页',exact:true})).toBeEnabled();
 const overviewCalls=signalRequests.length;
 await page.getByRole('button',{name:'查看完整原始点',exact:true}).click();
 for(const stats of Object.values(full.sampling) as any[])expect(stats.display_points).toBe(stats.raw_points);
 expect(full.sampling.map.raw_points).toBe(12319);
 expect(full.sampling.left.raw_points).toBe(4729);
 await expect(page.getByRole('button',{name:'切回抽稀概览',exact:true})).toBeEnabled();
 await expect(page.locator('.sampling-info')).toContainText('12319 / 12319');
 await page.locator('.sampling-info').screenshot({path:'../artifacts/13-raw-sampling.png'});
 await page.getByRole('button',{name:'切回抽稀概览',exact:true}).click();
 await expect(page.getByRole('button',{name:'查看完整原始点',exact:true})).toBeEnabled();
 expect(signalRequests.length).toBe(overviewCalls);
 await page.getByRole('button',{name:'查看完整原始点',exact:true}).click();
 await expect(page.getByRole('button',{name:'切回抽稀概览',exact:true})).toBeEnabled();
 expect(signalRequests.length).toBe(overviewCalls);
 await page.getByLabel('横轴时间显示').selectOption('elapsed');
 await page.getByRole('button',{name:/02 检查质量/}).click();
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('car-lab:last-completed-run:v1')!));
 const writes:string[]=[];
 await page.route('**/api/**',route=>{if(route.request().method()==='POST'){writes.push(route.request().url());return route.abort();}return route.continue();});
 await page.reload();
 await expect(page.locator('.local-resume')).toContainText(saved.run_id.slice(0,8),{timeout:60000});
 await expect(page.getByRole('heading',{name:'检查质量 / 02',exact:true})).toBeVisible();
 await expect(page.getByLabel('横轴时间显示')).toHaveValue('elapsed');
 await expect(page.getByRole('button',{name:'重新计算',exact:true})).toBeEnabled();
 expect(writes).toEqual([]);
 await page.locator('.local-resume').screenshot({path:'../artifacts/14-local-restore.png'});
 expect(errors).toEqual([]);
});
