import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';

test('真实病例、无效窗口、标记、A/B、敏感性窗口与导出',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 let observedRun:any=null;page.on('response',async r=>{if(/\/api\/analyses\/[a-f0-9]{64}$/.test(r.url())&&r.ok())observedRun=await r.json();});
 const health=await (await request.get('/api/health')).json();expect(health.algorithm_version).toBe('1.0.0');
 const artifacts=path.resolve('../artifacts');fs.mkdirSync(artifacts,{recursive:true});
 const capture=async(name:string)=>{await expect(page.locator('.busy')).toHaveCount(0,{timeout:60000});await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(250);await page.screenshot({path:path.join(artifacts,name),fullPage:true});};
 const ann=await (await request.get('/api/cases/251/annotations')).json();
 await page.goto('/');await expect(page.getByRole('heading',{name:'看原始信号'})).toBeVisible();
 await page.getByRole('button',{name:'选择病例',exact:true}).click();
 await page.getByRole('button',{name:'选择病例 251',exact:true}).click();
 await expect(page.getByText('#251 · 71 岁')).toBeVisible();
 await page.getByRole('button',{name:/^(下载并分析|分析本地数据)$/}).click();
 await expect(page.getByRole('button',{name:'重新计算',exact:true})).toBeEnabled({timeout:60000});
 await page.getByRole('button',{name:/04 看一个窗口/}).click();
 await expect(page.getByTestId('window-inspector')).toBeVisible();
 await expect(page.getByTestId('window-inspector').getByText('null',{exact:true})).toBeVisible();
 await capture('01-real-strict-1440.png');
 await page.getByRole('button',{name:/02 检查质量/}).click();
 await page.locator('.quality-manual summary').click();
 await page.getByLabel('标记起点').fill('100');await page.getByLabel('标记终点').fill('160');
 await page.getByLabel('标记原因').fill('E2E 可撤销质量标记');
 await page.getByRole('button',{name:'添加排除',exact:true}).click();
 await expect(page.locator('.annotation-row').getByText('E2E 可撤销质量标记')).toBeVisible();
 await page.getByRole('button',{name:'撤销',exact:true}).click();
 await expect(page.locator('.annotation-row').getByText('E2E 可撤销质量标记')).toHaveCount(0);
 await page.getByRole('button',{name:'重做',exact:true}).click();
 await expect(page.locator('.annotation-row').getByText('E2E 可撤销质量标记')).toBeVisible();
 await page.getByRole('button',{name:'撤销',exact:true}).click();
 await expect(page.locator('.annotation-row').getByText('E2E 可撤销质量标记')).toHaveCount(0);
 await page.getByRole('button',{name:/06 做参数对比/}).click();
 await page.getByRole('button',{name:'将当前运行固定为 A'}).click();
 await page.getByLabel('配对模式').selectOption('relaxed');
 await page.getByRole('button',{name:'计算运行 B',exact:true}).click();
 await expect(page.locator('.ab-row').getByText('300s · 放宽 · 人工排除 开')).toBeVisible({timeout:60000});
 await capture('02-real-ab-1440.png');
 await page.getByRole('button',{name:/04 看一个窗口/}).click();
 const inspector=page.getByTestId('window-inspector');await expect(inspector.locator('.metrics').getByText('24 / 30',{exact:true})).toBeVisible();
 // The exact pair table independently reproduces the backend result.
 const response=await page.request.get('/api/cases/251');expect(response.ok()).toBeTruthy();
 const displayed=await inspector.locator('.metrics strong').first().innerText();expect(displayed).not.toBe('null');
 const pairs=await inspector.locator('tbody tr').evaluateAll(rows=>rows.filter(r=>r.lastElementChild?.textContent?.startsWith('合格')).map(r=>[Number(r.children[1].textContent),Number(r.children[2].textContent)]));
 const mx=pairs.reduce((s,p)=>s+p[0],0)/pairs.length,my=pairs.reduce((s,p)=>s+p[1],0)/pairs.length;
 const numerator=pairs.reduce((s,p)=>s+(p[0]-mx)*(p[1]-my),0),denominator=Math.sqrt(pairs.reduce((s,p)=>s+(p[0]-mx)**2,0)*pairs.reduce((s,p)=>s+(p[1]-my)**2,0));
 expect(Math.abs(numerator/denominator-Number(displayed))).toBeLessThan(.00051);
 await page.getByLabel('拖动时间窗口').focus();await page.getByLabel('拖动时间窗口').press('Home');
 await expect(inspector.getByText('null',{exact:true})).toBeVisible();
 // Click an actual ECharts output symbol (case 251's full-range axis is 0–500 min).
 const validWindow=observedRun.windows.find((w:any)=>w.side==='left'&&w.cox!==null);
 const coxChart=page.getByRole('img',{name:'左右 COx 与无结果点，可点击每一个输出查看窗口',exact:true});
 const chartBox=await coxChart.boundingBox();
 await coxChart.click({position:{x:58+(validWindow.end/60/500)*(chartBox!.width-86),y:34+(1-validWindow.cox)/2.15*(265-82)}});
 await expect(inspector.locator('.metrics strong').first()).not.toHaveText('null');
 await page.getByRole('button',{name:/06 做参数对比/}).click();
 await page.getByLabel('窗口秒数').selectOption('600');await page.getByRole('button',{name:'计算运行 B',exact:true}).click();
 await expect(page.locator('.ab-row').getByText('600s · 放宽 · 人工排除 开')).toBeVisible({timeout:60000});
 await page.getByLabel('窗口秒数').selectOption('300');await page.getByRole('button',{name:'计算运行 B',exact:true}).click();
 await expect(page.locator('.ab-row').getByText('300s · 放宽 · 人工排除 开')).toBeVisible({timeout:60000});
 await expect(page.locator('.busy')).toHaveCount(0,{timeout:60000});
 await page.getByRole('button',{name:/04 看一个窗口/}).click();
 await expect(page.getByTestId('window-inspector')).toBeVisible();
 if(await page.locator('.config-panel').isVisible())await page.getByRole('button',{name:'参数',exact:true}).click();
 await capture('03-real-window-1440.png');
 await inspector.screenshot({path:path.join(artifacts,'06-window-inspector-detail.png')});
 await page.setViewportSize({width:1280,height:1000});
 await capture('04-real-window-1280.png');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.getByRole('button',{name:/03 做时间平均/}).click();
 await page.getByRole('button',{name:/展开第/}).click();
 await expect(page.getByRole('heading',{name:/的全部输入观测/})).toBeVisible();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'导出学习报告'}).click();
 await (await download).saveAs(path.join(artifacts,'browser-learning-report.zip'));
 const current=await (await request.get('/api/cases/251/annotations')).json();
 await request.post('/api/cases/251/annotations',{data:{version:current.version,items:ann.items}});
 expect(errors).toEqual([]);
});

test('合成模式与强制零方差仍可解释',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'合成信号实验室'}).click();
 await page.getByLabel('合成场景').selectOption('constant');await page.getByRole('button',{name:'运行实验',exact:true}).click();
 await expect(page.locator('.busy')).toHaveCount(0,{timeout:60000});
 await page.getByRole('button',{name:/04 看一个窗口/}).click();
 await expect(page.getByTestId('window-inspector')).toBeVisible();
 await page.getByLabel('拖动时间窗口').focus();await page.getByLabel('拖动时间窗口').press('End');
 await expect(page.getByTestId('window-inspector').getByText('零方差：相关未定义',{exact:true})).toBeVisible();
 await expect(page.locator('.population')).toHaveText('合成演示 · 不是真实病例');
 await page.screenshot({path:'../artifacts/05-synthetic-null.png',fullPage:true});
});

test('首次离线显示错误与合成替代入口',async({page})=>{
 await page.route('**/api/cases',route=>route.fulfill({json:[]}));
 await page.route('**/api/catalog',route=>route.fulfill({json:null}));
 await page.route('**/api/catalog/refresh',route=>route.fulfill({status:503,json:{detail:'离线：无法访问 VitalDB'}}));
 await page.goto('/');await page.getByRole('button',{name:'选择病例',exact:true}).click();
 await page.getByRole('button',{name:'更新官方索引'}).click();
 await page.getByLabel('关闭病例选择').click();
 await expect(page.getByRole('alert')).toContainText('离线');
 await expect(page.getByRole('button',{name:'合成信号实验室'})).toBeVisible();
});
