import {test,expect} from '@playwright/test';

test('NIRS规则预览、重算前后对照与原始表清洗值',async({page})=>{
 await page.goto('./');
 await expect(page.locator('.browser-runtime')).toContainText('轻量浏览就绪',{timeout:180000});
 await page.getByRole('button',{name:'合成信号实验室'}).click();
 await page.getByRole('button',{name:'运行实验',exact:true}).click();
 await expect(page.locator('.busy')).toHaveCount(0,{timeout:60000});
 await page.getByRole('button',{name:/02 检查质量/}).click();
 const comparison=page.getByTestId('quality-comparison');
 const left=comparison.getByTestId('quality-comparison-left');
 await expect(left.getByTestId('after-count')).toHaveText('361');
 const before=await left.getByTestId('before-range').textContent();
 await page.getByRole('button',{name:'展开 NIRS 质控学习'}).click();
 await page.getByLabel('NIRS范围下限').fill('90');
 await expect(page.getByTestId('raw-anomalies-left')).toContainText('361 / 361',{timeout:30000});
 await expect(page.getByTestId('raw-anomalies-left')).toContainText('排除 361 点');
 await expect(left.getByTestId('after-count')).toHaveText('361');
 await expect(page.getByTestId('quality-comparison-stale')).toBeVisible();
 await page.getByRole('button',{name:'应用 NIRS 质控并重算'}).click();
 await expect(left.getByTestId('after-count')).toHaveText('0',{timeout:60000});
 await expect(left.getByTestId('before-range')).toHaveText(before!);
 await expect(left.getByTestId('after-range')).toHaveText('—');
 await expect(page.getByTestId('quality-comparison-stale')).toHaveCount(0);
 await page.getByLabel('原始表通道').selectOption('left');
 await expect(page.getByRole('columnheader',{name:'NIRS_clean',exact:true})).toBeVisible();
 await expect(page.getByTestId('raw-data-panel').locator('tbody tr').first()).toContainText('NaN');
 await page.getByLabel('NIRS超界处理').selectOption('review');
 await expect(page.getByTestId('raw-anomalies-left')).toContainText('排除 0 点 · 仅提示 361 点',{timeout:30000});
 await expect(left.getByTestId('after-count')).toHaveText('0');
 await page.getByRole('button',{name:'应用 NIRS 质控并重算'}).click();
 await expect(left.getByTestId('after-count')).toHaveText('361',{timeout:60000});
 await expect(page.getByRole('alert')).toHaveCount(0);
 await comparison.screenshot({path:'../artifacts/quality-comparison-pages.png'});
 await page.getByLabel('NIRS范围下限').fill('95');
 await expect(page.getByRole('button',{name:'应用 NIRS 质控并重算'})).toBeDisabled();
 await page.getByLabel('NIRS范围下限').fill('90');
 await page.reload();
 await page.getByRole('button',{name:'恢复上次分析'}).click();
 await expect(page.locator('.browser-runtime')).toContainText('计算内核就绪',{timeout:180000});
 await expect(left.getByTestId('after-count')).toHaveText('361',{timeout:60000});
 await expect(page.getByTestId('raw-anomalies-left')).toContainText('仅提示 361 点',{timeout:30000});
});
